# Generated by Django 4.2 on 2023-04-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cricbuzz.basemodel",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("description", models.TextField()),
                ("thumbnail", models.ImageField(upload_to="")),
                ("is_premium", models.BooleanField()),
                ("is_video", models.BooleanField()),
                ("is_featured", models.BooleanField()),
            ],
            bases=("cricbuzz.basemodel",),
        ),
    ]
