# Generated by Django 4.2 on 2023-04-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cricbuzz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cricbuzz.basemodel",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("description", models.TextField(null=True)),
                ("features", models.TextField()),
                ("price", models.FloatField()),
            ],
            bases=("cricbuzz.basemodel",),
        ),
        migrations.AlterField(
            model_name="data",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="data",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
